version: '3.8'
services:

  rabbitmq-delta:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq
      - rabbit-log:/var/log/rabbitmq

  queuemanager:
    image: queuemanager-docker:delta
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq-delta
    ports:
      - "8080:8080"
    depends_on:
      - "rabbitmq-delta"

volumes:
  rabbit-data:
  rabbit-log:
